In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1


In [ ]:
print(load_diabetes)

<function load_diabetes at 0x79ac26856200>


In [ ]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

x = diabetes.data
y = diabetes.target

print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [ ]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

## Using Sklearn

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
x_train.shape,x_test.shape

((353, 10), (89, 10))

In [ ]:
reg = LinearRegression()

In [ ]:
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = reg.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

0.4399338661568968

In [ ]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
reg.intercept_

np.float64(151.88331005254167)

## USing custome bulit Linear Regression

In [ ]:
class meraLR:
  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self,x_train,y_train):
    x_train = np.insert(x_train,0,1,axis = 1)

    # Calculet the coeffs

    betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self,x_test):
    y_pred = np.dot(x_test,self.coef_) + self.intercept_
    return y_pred

In [ ]:
lr = meraLR()

In [ ]:
lr.fit(x_train,y_train)

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

0.43993386615689634

In [ ]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
lr.intercept_

np.float64(151.88331005254165)